export const REQUEST = {
  title: 'طلب الاشتراك',
  description: 'طلبك هو خطوتك الأولى للاستفادة من مشاريع تنال.',
  breadcrumbHistory: ['طلب الاشتراك'],
  TextFields: [
    {
      name: 'fullName',
      label: 'الاسم بالكامل',
      type: 'text',
      multiline: false,
    },
    {
      name: 'email',
      label: 'البريد الإلكتروني',
      type: 'email',
      multiline: false,
    },
    {
      name: 'mobile',
      label: 'رقم الجوال',
      type: 'tel',
      multiline: false,
    },
    {
      name: 'residenceCountry',
      label: 'مكان الإقامة: الدولة',
      type: 'text',
      multiline: false,
    },
    {
      name: 'residenceCity',
      label: 'مكان الإقامة: المدينة',
      type: 'text',
      multiline: false,
    },
    {
      name: 'howDidYouKnowUs',
      label: 'كيف عرفت عن شركة تنال الأولى للاستثمار؟',
      type: 'select',
      selectOptions: [
        { value: 'وسائل التواصل الاجتماعي', label: 'وسائل التواصل الاجتماعي' },
        { value: 'إحالة من شخص آخر', label: 'إحالة من شخص آخر' },
        { value: 'محرك بحث', label: 'محرك بحث' },
        { value: 'حدث أو مؤتمر', label: 'حدث أو مؤتمر' },
        { value: 'أخرى', label: 'أخرى' },
      ],
      multiline: false,
    },
    {
      name: 'currentEmployer',
      label: 'جهة العمل الحالية',
      type: 'text',
      multiline: false,
    },
    {
      name: 'currentPosition',
      label: 'المنصب/المسمى الوظيفي',
      type: 'text',
      multiline: false,
    },
    {
      name: 'linkedInProfile',
      label: 'رابط صفحتك على LinkedIn',
      type: 'url',
      multiline: false,
    },
    {
      name: 'twitterProfile',
      label: 'حساب Twitter-X',
      type: 'url',
      multiline: false,
    },
    {
      name: 'otherSocialMedia',
      label: 'أي حساب تواصل اجتماعي آخر ترغب في مشاركته',
      type: 'url',
      multiline: false,
    },
    {
      name: 'desiredProject',
      label: 'ما هو المشروع الذي تريد الانضمام له؟',
      type: 'select',
      selectOptions: [
        { value: 'الخرج', label: 'الخرج' },
        { value: 'احد المسارحة', label: 'احد المسارحة' },
        { value: 'المدينة المنورة', label: 'المدينة المنورة' },
        { value: 'الرياض', label: 'الرياض' },
      ],
      multiline: false,
    },
    {
      name: 'desiredServices',
      label: 'ما هي الخدمات التي تريد الاستفادة منها؟',
      type: 'text',
      multiline: false,
    },
    {
      name: 'notes',
      label: 'ملاحظات أخرى',
      type: 'text',
      multiline: true,
      rows: 5,
      sx: { mt: 2 },
    },
  ],
};
